backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: /assets

collections:
  - name: "Home"
    label: "Home"
    folder: "content/home"
    create: false
    delete: false
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    editor:
      preview: false
    fields:
      - {
          label: "Title",
          name: "title",
          widget: "string",
          hint: "title of node",
        }
      - { label: "home-content", name: "body", widget: "markdown" }
  - name: "About"
    label: "About"
    folder: "content/about"
    delete: false
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    editor:
      preview: false
    fields:
      - {
          label: "Title",
          name: "title",
          widget: "string",
          hint: "title of node",
        }
      - { label: "about-content", name: "body", widget: "markdown" }
  - name: "Drivers Improvement"
    label: "Drivers Improvement"
    folder: "content/drivers-improvement"
    delete: false
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    editor:
      preview: false
    fields:
      - {
          label: "Title",
          name: "title",
          widget: "string",
          hint: "title of node",
        }
      - { label: "improvement-title", name: "string", widget: "string" }
      - { label: "improvement-content", name: "body", widget: "markdown" }
  - name: "Virginia DMC"
    label: "Virginia DMC"
    folder: "content/drivers-manual"
    delete: false
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    editor:
      preview: false
    fields:
      - {
          label: "Title",
          name: "title",
          widget: "string",
          hint: "title of node",
        }
      - { label: "drivers-manual-title", name: "string", widget: "string" }
      - { label: "drivers-manual-content", name: "body", widget: "markdown" }
  - name: "Courses"
    label: "Courses"
    folder: "content/courses"
    delete: true
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    editor:
      preview: false
    fields:
      - {
          label: "Title",
          name: "title",
          widget: "string",
          hint: "title of node",
        }
      - { label: "description", name: "body", widget: "markdown" }
  - name: "FAQ"
    label: "FAQ"
    folder: "content/faq"
    delete: false
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    editor:
      preview: false
    fields:
      - {
          label: "Title",
          name: "title",
          widget: "string",
          hint: "title of node",
        }
      - { label: "faq-content", name: "body", widget: "markdown" }
  - name: "Online Training"
    label: "Online Training"
    folder: "content/online-training"
    delete: false
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    editor:
      preview: false
    fields:
      - {
          label: "Title",
          name: "title",
          widget: "string",
          hint: "title of node",
        }
      - { label: "training-content", name: "body", widget: "markdown" }
  - name: "News"
    label: "News"
    folder: "content/news"
    delete: false
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    editor:
      preview: false
    fields:
      - {
          label: "Title",
          name: "title",
          widget: "string",
          hint: "title of node",
        }
      - { label: "news-content", name: "body", widget: "markdown" }
  - name: "Products"
    label: "Products"
    folder: "content/products"
    delete: false
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    editor:
      preview: false
    fields:
      - {
          label: "Title",
          name: "title",
          widget: "string",
          hint: "title of node",
        }
      - { label: "product-name", name: "string", widget: "string" }
      - { label: "product-price", name: "price", widget: "number" }
      - {
          label: "product-sale",
          name: "number",
          widget: "number",
          required: false,
        }
  - name: "Form"
    label: "Form"
    folder: "content/form"
    delete: false
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    editor:
      preview: false
    fields:
      - {
          label: "Title",
          name: "title",
          widget: "string",
          hint: "title of node",
        }
      - { label: "form-content", name: "body", widget: "markdown" }
  - name: "Footer"
    label: "Footer"
    folder: "content/footer"
    delete: false
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Phone Number", name: "en-phone", widget: "string" }
      - { label: "Contact Hours", name: "contact-hours", widget: "string" }
      - { label: "Facebook link", name: "fb-link", widget: "string" }
